import Head from 'next/head'

import type { AppProps } from 'next/app'
import State from '@/store/context/navigateContext'

import '@/styles/main.css'
import '@/styles/globals.css'

export default function App({ Component, pageProps }: AppProps) {
	return (
		<State>
			<Head>
				<title>Miguel Gomez - Quick Portfolio Page</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Component {...pageProps} />
		</State>
	)
}
