import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import About from '@/components/About'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<div className='h-screen bg-[rgb(36,36,36)] z-0 snap-y snap-mandatory overflow-scroll scrollbar-thin scrollbar-track-gray-500/10 scrollbar-thumb-[#ce8e04]/80'>
				<Head>
					<title>Create Next App</title>
					<meta name='description' content='Generated by create next app' />
					<meta name='viewport' content='width=device-width, initial-scale=1' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<main>
					<section id='about-me'>
						<About />
					</section>
				</main>
			</div>
		</>
	)
}
